- pkg/controller/group/group_controller_test.go
- pkg/controller/group/suite_test.go
- pkg/webhook/validates/suite_test.go
When unit test, metrics start and serving on port 8080. If port 8080 has been bind, unit test will failed. So we disable the metrics serving in unit tests.
In Context "has more than 10 patches for the group", BeforeEach sometimes can't generate 10 patches because of it is possible that several endpoint update event were combined together in queue, cause failure in the test.
> fix unit tests failed on lynx controller

- deploy/crds/policyrule.lynx.smartx.com_policyrules.yaml
- pkg/agent/controller/policyrule/policyrule_controller.go
- pkg/agent/controller/policyrule/policyrule_controller_test.go
- pkg/apis/policyrule/v1alpha1/policyrule_types.go
- pkg/controller/policy/cache/helper.go
- pkg/controller/policy/cache/rule.go
To prevent policy rule from adding repeatedly, use hash of policyRule.Spec as flow key.
> use hash of policyRule.Spec as flow key

- cmd/lynx-agent/main.go
- pkg/monitor/agent.go
Libvirt created endpoint(VM) with specific ovsdb external-ids field named
"attached-mac" in its interface table. We use this field to monitor the local
endpoint create/delete event, and setup related local endpoint flow
> add localendpoint accordding to local ovsdb interface status

- pkg/monitor/agent.go
Correct receiver name accroding to error message from golint.
Signed-off-by: Kai Zhang <kyle@smartx.com>
> fix(agent): fix golint error

- go.mod
- go.sum
- tests/e2e/cases/e2e_test.go
- tests/e2e/framework/endpoint/tower/provider.go
Reset resource before start e2e, residual resources could cause the test to fail.
Tower provider use HTTP retry client, fix e2e failure due to unexpected HTTP connection failure.
> Fix unexpected e2e failure on elf environment

- cmd/lynx-controller/main.go
- plugin/tower/pkg/register/manager.go
- plugin/tower/pkg/register/manager_test.go
Add tower plugin to lynx-controller manager, default disable the plugin.
These flags will add to lynx-controller:
```shell
-plugins.tower.address string
Tower connection address
-plugins.tower.enable
If true, tower plugin will start (default false)
-plugins.tower.password string
Tower user password for authenticate
-plugins.tower.resync-period duration
Controller resync period (default 10h0m0s)
-plugins.tower.username string
Tower user name for authenticate
-plugins.tower.usersource string
Tower user source for authenticate
-plugins.tower.worker-number uint
Controller worker number (default 10)
```
> add tower plugin to lynx-controller

- pkg/controller/endpoint/endpoint_controller.go
- pkg/controller/endpoint/endpoint_controller_test.go
- pkg/webhook/validates/crd_validate.go
This PR:
1. Add iface indexer cache for endpoint controller, improve the efficiency of fetch endpoint status. #94 
2. Fix and add endpoint controller test cases.
3. Fix validate webhook on endpoint update.
> endpoint controller add iface indexer cache

- pkg/controller/policy/policy_controller.go
- tests/e2e/cases/security_mode.go
In code `for portNumber := begin; portNumber <= end; portNumber++`, loop continues while `portNumber <= end`.
If `end = 65535`, the loop won't stop because of int16 is always smaller than 65535.
> Fix infinite loop caused by uint64 overflow

- plugin/tower/pkg/client/types.go
- plugin/tower/pkg/informer/reflector.go
When subscript objects from the tower, delete object may get an event with nil object. So we get the delete object id from filed previousValues.
> fix(plugin-tower): delete object get nil object value

- plugin/tower/pkg/controller/controller.go
When the watch deletion event was missed, cache.DeletedFinalStateUnknown(instead of *cache.DeletedFinalStateUnknown) will be received.
> fix(plugin-tower): panic caused by the wrong type asserts as *cache.DeletedFinalStateUnknown

- .golangci.yml
- deploy/crds/security.lynx.smartx.com_endpoints.yaml
- deploy/crds/security.lynx.smartx.com_securitypolicies.yaml
- pkg/apis/security/v1alpha1/types.go
- pkg/client/clientset_generated/clientset/typed/security/v1alpha1/endpoint.go
- pkg/client/clientset_generated/clientset/typed/security/v1alpha1/fake/fake_endpoint.go
- pkg/client/clientset_generated/clientset/typed/security/v1alpha1/fake/fake_security_client.go
- pkg/client/clientset_generated/clientset/typed/security/v1alpha1/fake/fake_securitypolicy.go
- pkg/client/clientset_generated/clientset/typed/security/v1alpha1/security_client.go
- pkg/client/clientset_generated/clientset/typed/security/v1alpha1/securitypolicy.go
- pkg/client/informers_generated/externalversions/security/v1alpha1/endpoint.go
- pkg/client/informers_generated/externalversions/security/v1alpha1/interface.go
- pkg/client/informers_generated/externalversions/security/v1alpha1/securitypolicy.go
- pkg/client/listers_generated/security/v1alpha1/endpoint.go
- pkg/client/listers_generated/security/v1alpha1/expansion_generated.go
- pkg/client/listers_generated/security/v1alpha1/securitypolicy.go
- pkg/controller/group/group_controller_test.go
- pkg/controller/policy/policy_controller.go
- pkg/controller/policy/policy_controller_test.go
- pkg/webhook/validates/crd_validate_test.go
- plugin/tower/cmd/main.go
- plugin/tower/cmd/options.go
- plugin/tower/pkg/controller/controller.go
- plugin/tower/pkg/controller/controller_test.go
- plugin/tower/pkg/register/manager.go
- tests/e2e/cases/security_test.go
- tests/e2e/framework/endpoint/netns/provider.go
- tests/e2e/framework/framework.go
- tests/e2e/tools/e2ectl/command/policy.go
To support Kubernetes NetworkPolicy, we need to change endpoint and security as no namespace resources.
issue: #131
> Add namespace for endpoint and securitypolicy

- deploy/crds/security.lynx.smartx.com_securitypolicies.yaml
- pkg/apis/security/v1alpha1/helper.go
- pkg/apis/security/v1alpha1/types.go
- pkg/apis/security/v1alpha1/zz_generated.deepcopy.go
- pkg/controller/policy/policy_controller.go
- pkg/controller/policy/policy_controller_test.go
- tests/e2e/cases/security_test.go
- tests/e2e/tools/e2ectl/command/policy.go
**Why do we need this ?**
Kubernetes NetworkPolicy supports PolicyTypes, described below:
> Each NetworkPolicy includes a policyTypes list which may include either Ingress, Egress, or both. The policyTypes field indicates whether or not the given policy applies to ingress traffic to selected pod, egress traffic from selected pods, or both. If no policyTypes are specified on a NetworkPolicy then by default Ingress will always be set and Egress will be set if the NetworkPolicy has any egress rules.
To support Kubernetes NetworkPolicy #131 , we need add this field in SecurityPolicy.
**Dependent PR #133 Merge First**
> Support PolicyTypes for SecurityPolicy

- Makefile
- cmd/lynx-controller/main.go
- deploy/lynx-controller/webhook.yaml
- deploy/lynx.yaml
- tests/e2e/config/webhook.yaml
In pre version, secret was generated by controller, so that, after uninstallation, the secret will
still reamin in k8s. When install next time, contoller cannot not create a new secret, it will occur
an error.
This commit will get and check if someone has updated secret, or the
controller will update it.
> fix(controller): modify webhook generation

- pkg/monitor/agent_test.go
agent need more time to start with more complex datapath.
> test(agentmonitor): extend timeout time for agent monitor test

- cmd/everoute-controller/main.go
- deploy/everoute-controller/webhook.yaml
- deploy/everoute.yaml
- tests/e2e/config/webhook.yaml
warning info: admissionregistration.k8s.io/v1beta1 ValidatingWebhookConfiguration is deprecated in v1.16+,
unavailable in v1.22+; use admissionregistration.k8s.io/v1 ValidatingWebhookConfiguration.
Actually, CR could not be created in v1.21.5, there will be an error in conversion.
> refactor(k8s-api): upgrade webhook from v1beta to v1

- deploy/crds/security.everoute.io_endpoints.yaml
- deploy/crds/security.everoute.io_globalpolicies.yaml
- deploy/crds/security.everoute.io_securitypolicies.yaml
- deploy/everoute.yaml
- docs/content/en/docs/reference/apidocs.html
- pkg/apis/security/v1alpha1/types.go
- pkg/openapi/openapi_generated.go
fix #190 
Add comments in file `pkg/apis/security/v1alpha1/types.go`.
Other file changes were generated by `make docker-generate`.
> Add comments for api types

- pkg/agent/cniserver/server.go
ovs will check veth name
```
bool
ovsdb_parser_is_id(const char *string)
{
unsigned char c;
c = *string;
if (!isalpha(c) && c != '_') {
return false;
}
for (;;) {
c = *++string;
if (c == '\0') {
return true;
} else if (!isalpha(c) && !isdigit(c) && c != '_') {
return false;
}
}
}
```
> fix(cniserver): add prefix "_" for veth pair name

- pkg/controller/k8s/network_policy_controller.go
In networkPolicy, port was defined with `*intstr.IntOrString`
`port.StrVal` should be used for `intstr.IntOrString`
`port.String()` should be used for `*intstr.IntOrString`
Otherwise, the string value will be empty
> fix: port in networkPolicy could not sync to securityPolicy

- pkg/agent/controller/policyrule/policyrule_controller_test.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/multiBridgeDatapath_test.go
- pkg/agent/datapath/utils.go
1. To avoid local to local packet that redirects from cls bridge
forwarding multiple times, set local to policy
bridge patch port with no-flood mode,
2. Set bridge with OpenFlow10-OpenFlow13 OpenFlow protocol version
Dependent on ofctrl PR34 https://github.com/everoute/ofnet/pull/34
> update bridge chain setup parameter

- deploy/crds/policyrule.everoute.io_policyrules.yaml
- deploy/everoute.yaml
- pkg/apis/policyrule/v1alpha1/policyrule_types.go
We can use `kubectl get policyrule` show policy details
```
$kubectl get policyrule -A
NAME    DIRECTION   RULETYPE      TIER    SRCIPADDR   DSTIPADDR           IPPROTOCOL   DSTPORT   DSTPORTMASK   ACTION
test    Ingress     DefaultRule   tier0               192.168.24.121/32                                        Drop
```
> Add kubectl printcolumn for policyrules

- pkg/agent/datapath/multiBridgeDatapath.go
Updated datapath config file with VDS id field as key and local
bridge name as value.  Thus, we should use the value of datapath config k-v pair instead of the key.
#238
> fix: correct ovs bridge name

- cmd/everoute-agent/main.go
- deploy/crds/agent.everoute.io_agentinfos.yaml
- deploy/everoute-controller/role.yaml
- deploy/everoute.yaml
- pkg/agent/controller/policyrule/policyrule_controller_test.go
- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/multiBridgeDatapath_test.go
- pkg/apis/agent/v1alpha1/types.go
- pkg/apis/agent/v1alpha1/zz_generated.deepcopy.go
- pkg/controller/endpoint/endpoint_controller.go
- pkg/controller/endpoint/endpoint_controller_perf_test.go
- pkg/controller/endpoint/endpoint_controller_test.go
- pkg/monitor/agent.go
- pkg/monitor/agent_test.go
- pkg/openapi/openapi_generated.go
- tests/e2e/framework/endpoint/netns/provider.go
- tests/e2e/framework/endpoint/netns/scripts.go
1. Agent take stateless ip learning logic, not save any of interface
state like ipset etc
2. Endpoint controller act as the stateful processing manager: save
interface ip set; ip set timeout management
> refactor ip address learning logic

- cmd/everoute-agent/main.go
- pkg/agent/datapath/clsBridge.go
- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/policyBridge.go
- pkg/agent/datapath/uplinkBridge.go
cni datapath need get pod CIDR from apiserver. 
While agent could not connection to apiserver, it will block the whole datapath init process.
> fix(cni): split cni datapath init and everoute datapath init

- pkg/agent/proxy/route.go
It will log error because cache not ready at startup. 
Update will be triggered with Node Create Event.
> fix(cni): remove updatNetwork at startup

- Makefile
default build will use /.cache, which needs root privilege
> build(code-gen): run code gen with root

- deploy/everoute-agent/role.yaml
- deploy/everoute.yaml
- pkg/agent/cniserver/server.go
1. endpoint status will be replaced will empty agentinfo, this sync op does not make sense.
2. agent will not watch endpoint
> fix(cni): remove useless endpoint ip sync

- deploy/everoute-agent/agent.yaml
- deploy/everoute.yaml
Default stategy is rolling update with maxUnavailable 1, that means we have to update agent one by one.
It will takes a long time for updating when there are lots of agents in cluster.
> chore(deploy): set agent update strategy to "update all at same time"

- go.mod
After replaces, it will be easier when other repos use everoute as a module
> chore: replace modules empty version with an explicit version

- build/images/release/Dockerfile
- build/images/unit-test/Dockerfile
ovs version in ubuntu source has been updated to 2.13.5-0ubuntu1.
we may build ovs from source code later.
> build: update ovs version in dockerfile

- Makefile
- cmd/everoute-agent/config.go
- deploy/everoute-agent/agent.yaml
- deploy/everoute.yaml
- pkg/constants/constants.go
- pkg/monitor/agent.go
- tests/e2e/scripts/agent-setup.sh
Before, we used a randomly generated uuid as agent name. 
Agent name is the name of agentinfo CR.
Now, we should match agent and endpoint,
so agentName must be able to correspond to agent.
> feat: use node name for agent name in kubernetes

- build/images/release/Dockerfile
"ip xx" command has been removed in ubuntu:20.04 by default.
> build: add iproute2 in base image

- plugin/tower/pkg/server/fake/server.go
- plugin/tower/pkg/server/fake/server_test.go
> fix(plugin-tower): data race when server immediately stop

- go.mod
- go.sum
- tests/e2e/framework/node/agent.go
**commit: [dump flows with prefix "cookie="](https://github.com/everoute/everoute/pull/470/commits/2f5221d17f10dbbea76b62c2413d9295a77fe6dc)**
We dump flows with the prefix "cookie=" to make sure e2e won't panic on the following flow result:
```
OFPST_FLOW reply (OF1.3) (xid=0x2): flags=[more]
cookie=0x4000000000009, duration=427501.390s, table=0, n_packets=157064305, n_bytes=69446849982, priority=300,ip actions=ct(table=1,zone=65520)
cookie=0x400000000000a, duration=427501.390s, table=0, n_packets=97589, n_bytes=4343847, priority=300,in_port=102 actions=output:201
cookie=0x400000000000b, duration=427501.390s, table=0, n_packets=20321227, n_bytes=1285196685, priority=300,in_port=201 actions=output:102
cookie=0x0, duration=427541.969s, table=0, n_packets=1038, n_bytes=108639, priority=0 …
```
> Fix everoute e2e on Tower

- plugin/tower/pkg/client/types.go
- plugin/tower/pkg/client/types_test.go
For some GraphQL servers(such as Prisma), the response error code is a number. We should handle the number or string error code.
> feat(plugin-tower): support number as graphql error code

- pkg/apis/group/v1alpha1/types.go
- pkg/client/clientset_generated/clientset/typed/group/v1alpha1/fake/fake_groupmembers.go
- pkg/client/clientset_generated/clientset/typed/group/v1alpha1/groupmembers.go
- pkg/client/informers_generated/externalversions/generic.go
Update resource name to match CRD.
```
NAME                  SHORTNAMES   APIGROUP            NAMESPACED   KIND
endpointgroups                     group.everoute.io   false        EndpointGroup
groupmembers                       group.everoute.io   false        GroupMembers
groupmemberspatches                group.everoute.io   false        GroupMembersPatch
```
> fix(clientset): update resource name from groupmemberses to groupmembers

- pkg/agent/controller/policy/cache/rule.go
ip: agent1
ip: agent1 agent2
-> ip: agent2
add new(v2) agent2
del old (v1) agent1 agent2
finally it will be **ip: {}**
del old (v1) agent1 agent2
add new(v2) agent2
> fix(policy): change apply order while updating patches

- go.mod
- go.sum
- pkg/agent/datapath/multiBridgeDatapath.go
previous lib: github.com/streamrail/concurrent-map
multiBridgeDatapath: L692-L698
Call map.Set inside IterBuffered
chan in IterBuffered may full under high pressure
> fix: replace concurrent-map with upstream lib to solve deadlock

- plugin/tower/pkg/client/client.go
- plugin/tower/pkg/client/client_test.go
- plugin/tower/pkg/client/request.go
- plugin/tower/pkg/client/request_test.go
Combine HTTP body reader and upload file reader, reduce the memory usage for copy file.
> refactor(plugin-tower): streaming upload file with graphql

- .github/workflows/ci.yaml
Sometimes, k8s e2e will get stuck. And we don't find the reason now, so set timeout for it
> ci: add timeout for k8s e2e

- .github/workflows/ci.yaml
- hack/kubesmartcluster.yaml.tmpl
set k8s e2e own runner with label pod-k8s-e2e to control k8s-e2e concurrency
> ci: set k8s e2e own runner

- pkg/agent/datapath/localBridgeOverlay.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/uplinkBridgeOverlay.go
When use kube-proxy, svc pkt will do DNAT in kernel through cnibr0-gw-local. After DNAT, it will request the endpoint IP's arp before pkt come back to cnibr0-gw-local. The PR add reply hostnetwork endpoint arp flow in local bridge
> fix: reply hostnetwork endpoint's arp in cnibr0-gw-local

- .github/workflows/build.yaml
- .github/workflows/ci.yaml
1、use pod runner to build image
2、add build cache
ci failed to build image, because pr source fork repo can't use everoute/everoute secrets. there has been test in https://github.com/everoute/everoute/actions/runs/6493999967 for build, and https://github.com/everoute/everoute/actions/runs/6493999975 for ci
> ci: add build cache

- deploy/chart/templates/crds/ipam.everoute.io_ippools.yaml
- deploy/chart/templates/everoute_ippool.yaml
- deploy/chart/values.yaml
- deploy/everoute.yaml
- go.mod
- go.sum
主要功能：
部署everoute时创建ippool everoute-built-in 用于给cnibr0-gw分配IP。
通过values可在部署everoute时配置 everoute-built-in ip池的 cidr,subnet，gatway。
默认everoute-built-in ip池的spec.private属性为true，不会从这个IP池中分配IP给其他Pod。
自测：
创建了ip池 everoute-built-in 
且从这个IP池中分配了两个IP分别给两个节点的cnibr0-gw网口
不会从这个IP池中分配IP给其他Pod
> feat: set gw ippool private

- cmd/everoute-agent/config.go
- cmd/everoute-agent/main.go
- pkg/agent/controller/ippool/controller.go
- pkg/agent/datapath/baseBridge.go
- pkg/agent/datapath/localBridgeOverlay.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/uplinkBridgeOverlay.go
- pkg/agent/datapath/utils.go
- pkg/agent/proxy/route.go
功能：
- 初始化ovs bridge时，在uplink bridge上添加 cnibr0-gw ip 子网的arp代答流表 以及集群内部IP转发流表。使得在k8s节点上能正常访问其他节点的cnibr0-gw IP 
- 初始化ovs bridge时，在uplink bridge上添加cnibr0-gw子网的gateway(即everoute-built-in ippool的gateway)的icmp代答，使得everoute-built-in ippool的gateway能被ping通
- watch 其他ippool，在local bridge上添加ippool对应子网的arp代答流表，使得Pod能正常请求自身所在子网的arp并得到回复
- watch 其他ippool，在local bridge上添加ippool对应gateway的icmp代答流表，使得Pod能ping通默认网关
- watch 其他ippool,  在uplink bridge上添加ippool对应子网的集群内部IP转发流表，使得Pod能正常访问其他节点的Pod IP
已进行的自测：
- Pod连通性：Pod 访问网关，Pod 访问本节点和其他节点的cnibr0-gw IP，Pod访问节点外IP，Pod访问同节点Pod, Pod访问跨节点Pod
- 节点访问Pod： 在节点上访问本节点Pod，在节点上访问其他节点Pod
- svc连通性: 在节点上访问clusterIP svc，在Pod内访问clusterIP svc，在k8s集群外部访问NodePort svc
> feat: watch ippool and setup ovsflow

- pkg/controller/k8s/node_controller_test.go
- pkg/controller/k8s/suite_test.go
ut概率失败原因：
k8smanager 通过go协程启动，如果运行单测的时候k8smanager还没有启动，那么单测会失败
解决方式：
k8smanager在启动过程中会等待cache同步，所以在运行单测之前等待cache同步，那么运行单测时，k8smanager大概率已经启动
> fix: node controller ut must run after k8smanager start

- .github/workflows/ci.yaml
- hack/kubesmartcluster_idc.yaml.tmpl
k8s e2e 能同时在7031和idc环境上运行
实现方式：
- 运行2个runnerdeployment，其label都是pod-k8s-e2e-v2，分别在7031集群和idc集群运行k8s e2e
- 在idc环境上运行的k8s集群的vip池为sdn2（172.21.253.0-172.21.253.30），在7031集群上运行的k8s集群的vip池为sdn1（192.168.65.1-100）。通过runner环境的环境变量PoolName区分。
- idc环境的ksc yaml为kubesmartcluster_idc.yaml.tmpl，7031环境为kubesmartcluster.yaml.tmpl。通过runner的环境变量Tmpl区分
> ci: k8s e2e run in idc

- cmd/everoute-agent/main.go
- cmd/everoute-controller/config.go
- cmd/everoute-controller/main.go
- deploy/chart/templates/config.yaml
- deploy/chart/templates/controller/role.yaml
- deploy/chart/values.yaml
- deploy/everoute.yaml
- go.mod
- pkg/constants/constants.go
- pkg/controller/ipam/endpoint.go
- pkg/controller/ipam/endpoint_test.go
- pkg/controller/ipam/suit_test.go
- pkg/ipam/everoute_ipam.go
- pkg/ipam/release_gw_ip.go
- pkg/ipam/release_gw_ip_test.go
- pkg/ipam/suit_test.go
- pkg/utils/cni.go
功能：
- watch gateway endpoint 删除事件，release 对应节点的gateway IP
- 周期任务判断已分配的cniused 类型的IP对应的endpoint和node是否存在，如果gateway endpoint和node都不存在，则release IP 
自测：
- 周期任务会删除IPPool status中endpoint和node都不存在的cniused类型的IP分配信息
- k8s集群扩容，增加1个节点，正常为新节点的gateway 分配IP
- k8s集群缩容，删除1个节点，正常回收被删除节点的gateway ip
> feat: release gateway ip

- pkg/monitor/suite_test.go
monitor 使用 k8s fake client 进行测试，fake client 实现有漏洞，informer 使用 fake client 在 list 和 watch 之间可能会丢事件。
如果 agentinfo create 事件丢失，monitor 则无法正常运行，一直尝试创建 agentinfo。但会因为 agentinfo 已存在失败。
此 PR 调整 monitor test 中 informer 的启动顺序，先启动 informer，然后启动 monitor。防止产生上述问题。
> test(monitor): start and wait informer before monitor

- .github/workflows/ci.yaml
- hack/ippool_ci.yaml
- hack/kubesmartcluster.yaml.tmpl
- hack/kubesmartcluster_idc.yaml.tmpl
1. sks 1.2需要通过 stub-cni类型表示不安装cni插件 (ci环境sks已升级至1.2)
2. 使用everoute ipam 在某个ip池剩下极少数IP的情况下，若多个Pod创建请求IP，会导致Pod需要重试多次才能创建成功 [ipam issue](https://github.com/everoute/ipam/issues/33)。这会导致ci有概率失败，所以ci中暂时只使用1个IP池
> ci: cooperate with sks1.2

- build/images/release/Dockerfile
- build/script/init_agent
- cmd/everoute-agent/config.go
- cmd/everoute-agent/main.go
- cmd/everoute-controller/config.go
- cmd/everoute-controller/main.go
- deploy/chart/templates/config.yaml
- deploy/chart/values.yaml
- deploy/everoute.yaml
- go.mod
- go.sum
- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/localBridgeOverlay.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/proxy/iptables/base.go
- pkg/agent/proxy/iptables/overlay_mode.go
- pkg/agent/proxy/iptables/proxy_iptables.go
- pkg/agent/proxy/iptables/proxy_iptables_test.go
- pkg/agent/proxy/overlay_route.go
- pkg/agent/proxy/route.go
- pkg/constants/constants.go
1. add config: kubeProxyReplace, apiServer,svcInternalIP
2. create patch port for bridge nat and uplink in init-agent
3. create ipset,iptables,route for kubeproxy replace feature
test:
- route:
- iptables:
- ipset:
> add kube-proxy replace config and init iptables route

- build/images/unit-test/Dockerfile
- pkg/agent/controller/overlay/suit_test.go
- pkg/agent/controller/policy/suite_test.go
- pkg/agent/controller/proxy/controller_test.go
- pkg/agent/controller/proxy/suit_test.go
- pkg/controller/group/suite_test.go
- pkg/controller/ipam/suit_test.go
- pkg/controller/k8s/suite_test.go
- pkg/controller/policy/suite_test.go
- pkg/webhook/validates/suite_test.go
use kube-apiserver v1.24 in unit test image
must stop controller runtime before stop kube-apiserver
> ci: use kube-apiServer v1.24 in unit test image

- pkg/agent/datapath/multiBridgeDatapath_test.go
- pkg/agent/datapath/policyBridge.go
fix: https://github.com/everoute/analyzer/issues/254, [ER-708](http://jira.smartx.com/browse/ER-708)
design document: https://docs.google.com/document/d/1L-Xikqh2RGwV2-JP9CUW_iPyZVs5-6lc3cZgsS-jJF4
ct label usage: https://docs.google.com/spreadsheets/d/1jADYgo0tt1-Q9GYglZkRoiDRn0VGHyj2zNVNDPxgxLU
e2e test report: https://docs.google.com/document/d/1zCV1u_S8AujXj6NOJun_dVasjUKbl7B6_aF0mQ7HK_I/edit
> fix(ER-708): skip match monitor tier3 ingress when ct match monitor drop

- pkg/constants/constants.go
- pkg/controller/endpoint/endpoint_controller.go
- pkg/controller/endpoint/suit_test.go
- pkg/monitor/agent.go
- pkg/monitor/agent_test.go
已验证场景：
- 添加虚拟机网卡
- 虚拟机网卡添加IP
- 添加ECP Pod IP
- 重启节点
> fix: check externalIDs when merge old ip to agentinfo

- pkg/agent/controller/policy/cache/rule.go
- pkg/agent/controller/policy/policy_controller.go
- pkg/agent/controller/policy/policy_controller_helper.go
- pkg/constants/constants.go
测试：
创建blocklist安全策略
```
apiVersion: security.everoute.io/v1alpha1
kind: SecurityPolicy
metadata:
name: zj-test-calico-block
namespace: tower-space
resourceVersion: "30808494"
uid: d9104152-3d3d-48cb-a188-24b5d23dee6f
spec:
appliedTo:
- endpointSelector:
matchLabels:
sks-cluster-name: test-calico
defaultRule: drop
egressRules:
- name: egress0
to:
- ipBlock:
cidr: 192.168.27.29/32
isBlocklist: true
policyTypes:
- Egress
priority: 50
securityPolicyEnforcementMode: work
tier: tier2
```
test-calico 虚拟机无法ping 通ip 192.168.27.29
查看流表，包含优先级为150（100+50），且drop 192.168.25.73(test-calico 虚拟机)->192.168.27.29流量的流表
> feat: implement securitypolicy priority and blocklist

- cmd/everoute-agent/config.go
- cmd/everoute-controller/config.go
这个url的check有问题，它不支持ip:port格式会报错，只能是单个ip或者完整url http://ip:port
apiserver 可选的填写方式为 ip:port 或者ip（默认端口是6443）
如果参数填错，无法连接apiserver， 进程起不来。所以这里可以不加校验
> fix(cni): delete error apiserver param check

- pkg/agent/proxy/iptables/overlay_mode.go
- pkg/agent/proxy/iptables/proxy_iptables.go
- pkg/agent/proxy/iptables/route_mode.go
- pkg/constants/constants.go
修改NodePort svc和 LB SVC 的节点导流 iptables 规则：
> fix(cni): support access to svc from local node

- plugin/tower/pkg/informer/factory.go
- plugin/tower/pkg/informer/reflector.go
- plugin/tower/pkg/schema/types.go
- plugin/tower/pkg/schema/types.graphqls
- plugin/tower/pkg/server/fake/graph/generated/generated.go
同 PR https://github.com/everoute/everoute/pull/837 用于 collector 调用 GRPC 接口
因为分支落后 main 太多，所以重新 cherry-pick 了 adapt-everoute-visualization 的相关 commit。又因为 main 中已经有 https://github.com/everoute/everoute/pull/837 的 commit，所以这个 PR 仅用于使分支 adapt-everoute-visualization 追上现有的 main 分支。
> Adapt everoute visualization cherry pick

- pkg/agent/datapath/baseBridge.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/rpcserver/collector.go
删掉了 FlowIDToVdsID，改为使用朴素实现。
在 BaseBridge上添加了一个函数：GetIndex，用来提供 bridge index
> fix(er-1128): return local bridge ID in rpc server
