- .github/workflows/ci.yaml
- .gitignore
- Makefile
- README.md
report lynx code coverage
add go race test
> add race test and cover test for lynx

- pkg/monitor/agent_test.go
Fix the data race caused by using the same ovsClient by monitor and test case.
> fix monitor unit test data race

- go.mod
- go.sum
- pkg/controller/group/group_controller_test.go
- pkg/controller/policy/policy_controller_test.go
replace github.com/contiv/libovsdb with github.com/smartxworks/libovsdb
fix miss error handling in unit test
add assert patch has been create in unit test
> fix tests failed in data race and go test

- Makefile
- codecov.yaml
Signed-off-by: Kai Zhang <kyle@smartx.com>
> refine coverage report

- pkg/agent/controller/policyrule/policyrule_controller.go
> support default policyrule with only src or dst ip match field

- deploy/crds/security.lynx.smartx.com_securitypolicies.yaml
- pkg/apis/security/v1alpha1/types.go
- pkg/controller/policy/policy_controller.go
- pkg/controller/policy/policy_controller_test.go
- pkg/webhook/validates/crd_validate.go
> securitypolicy: empty rule ports matches all ports

- pkg/controller/policy/policy_controller.go
Object with finalizers may be deleted from apiserver, handler delete request if object not found.
#37
> delete policy dependents if not found in cache

- pkg/monitor/agent.go
agentMonitor.getAgentInfo repeatedly call RLock, call Lock in the interval will cause deadlock.
> fix deadlock in agent monitor

- pkg/controller/policy/cache/rule.go
- pkg/controller/policy/policy_controller_test.go
policyIndexFunc get wrong policy name from ruleID, CompleteRules wouldn't delete after policy delete.
> fix get policy name from ruleID

- Makefile
- go.mod
- go.sum
- tests/e2e/README.md
- tests/e2e/cases/e2e_test.go
- tests/e2e/cases/security_test.go
- tests/e2e/doc.go
- tests/e2e/framework/framework.go
- tests/e2e/framework/scripts.go
- tests/e2e/scripts/agent-setup.sh
- tests/e2e/scripts/controlplane-setup.sh
- tests/e2e/scripts/e2e-reset.sh
- tests/e2e/scripts/e2e-setup.sh
- tests/e2e/tools/command/check.go
- tests/e2e/tools/command/group.go
- tests/e2e/tools/command/helper.go
- tests/e2e/tools/command/policy.go
- tests/e2e/tools/command/printer.go
- tests/e2e/tools/command/reach.go
- tests/e2e/tools/command/tier.go
- tests/e2e/tools/command/truthtable.go
- tests/e2e/tools/command/vm.go
- tests/e2e/tools/e2ectl.go
update e2e environment setup script
add lynx e2e tests cases
add e2ectl command tools
> add e2e test cases & e2e command tools

- pkg/monitor/agent.go
> fix fatal when register ovsdbEventHandler

- .github/workflows/ci.yaml
- Makefile
- tests/e2e/framework/scripts.go
- tests/e2e/scripts/agent-setup.sh
Add e2e runner job in github action.
Set attached-mac and uplink-port in interface external_ids.
> add e2e runner job in github action

- cmd/lynx-agent/main.go
- go.mod
- go.sum
- pkg/monitor/agent.go
- pkg/monitor/agent_test.go
Using ofnetAgent level endpoint add/del interface, make it consistent with the
uplink status management interface and other datapaths；
> Update to unified datapath local endpoint management interface

- .github/workflows/ci.yaml
Github action failed because apt failed to install packages.
Some package may have been updated, more: https://ubuntu.com/security/notices
> run apt update before apt install packages

- pkg/monitor/agent_test.go
> fix unit test failed to delete ovs-port

- deploy/crds/security.lynx.smartx.com_securitypolicies.yaml
- pkg/apis/security/v1alpha1/types.go
- pkg/controller/policy/cache/rule.go
- pkg/controller/policy/policy_controller.go
- pkg/controller/policy/policy_controller_test.go
- tests/e2e/cases/security_test.go
> generate symmetry rules for SymmetricMode policy

- plugin/tower/pkg/client/types.go
- tests/e2e/framework/config/config.go
> fix(e2e): login to tower before start e2e

- plugin/tower/pkg/controller/controller.go
- plugin/tower/pkg/controller/controller_test.go
> fix(plugin-tower): ignore invalid vm labels

- deploy/crds/agent.lynx.smartx.com_agentinfos.yaml
- deploy/crds/group.lynx.smartx.com_endpointgroups.yaml
- deploy/crds/group.lynx.smartx.com_groupmembers.yaml
- deploy/crds/group.lynx.smartx.com_groupmemberspatches.yaml
- deploy/crds/policyrule.lynx.smartx.com_policyrules.yaml
- deploy/crds/security.lynx.smartx.com_endpoints.yaml
- deploy/crds/security.lynx.smartx.com_securitypolicies.yaml
- deploy/crds/security.lynx.smartx.com_tiers.yaml
- pkg/apis/security/v1alpha1/types.go
- pkg/controller/policy/policy_controller.go
- pkg/controller/policy/policy_controller_test.go
- pkg/webhook/validates/crd_validate.go
- pkg/webhook/validates/crd_validate_test.go
> SecurityPolicy allow multiple port range separated by commas

- .github/workflows/ci.yaml
> Migration codecov from v1 to v2

- pkg/controller/k8s/pod_controller.go
- pkg/controller/k8s/pod_controller_test.go
endpoint selector in SecurityPolicy will select corresponding endpoints according to labels in
endpoint.
> fix(pod-controller): sync pod label into endpoint

- cmd/lynx-controller/main.go
- deploy/lynx-controller/role.yaml
- pkg/controller/k8s/network_policy_controller.go
- pkg/controller/k8s/network_policy_controller_test.go
- pkg/controller/k8s/pod_controller.go
- pkg/controller/k8s/pod_controller_test.go
- pkg/controller/k8s/suite_test.go
This controller will sync networkPolicy into SecurityPolicy.
> feat(controller): add networkPolicy controller

- tests/e2e/scripts/e2e-setup.sh
> test(e2e): update timeout to 60s

- pkg/agent/datapath/uplinkBridge.go
Agent failover logic maybe flush uplink default flow, we should init
uplink bridge default flow once agent restart, same as other bridge.
> add uplink bridge default flow init logic

- pkg/agent/cniserver/server.go
Before, veth pair was named veth-"ns". 
But in some cases, kubelet will not pass interface info to cni DELETE op. 
So that, DELETE process will be failed and ip will not be released.
#176
> fix(cni-server): use container id to name veth pair

- build/images/release/Dockerfile
- build/script/agent_init_probe
- build/script/init_agent
- deploy/everoute-agent/agent.yaml
- deploy/everoute.yaml
host does not need to install ovs anymore for k8s
> setup ovs in container

- pkg/controller/policy/group_generator.go
- pkg/controller/policy/group_generator_test.go
> Change semantics of EndpointSelector in SecurityPolicyPeer

- pkg/agent/datapath/localBridge.go
update local bridge vlanInputTable default flow from drop to
passthrough
> Update local vlan input table default flow

- go.mod
- go.sum
- pkg/agent/datapath/multiBridgeDatapath.go
New ovsdbDriver only if ovs bridge already exists
> Update ofctrl library

- build/script/init_agent
- cmd/everoute-agent/config.go
- cmd/everoute-agent/main.go
- deploy/everoute-agent/agent.yaml
- deploy/everoute-controller/controller.yaml
- deploy/everoute.yaml
- go.sum
- pkg/agent/cniserver/server.go
- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/utils.go
- pkg/agent/proxy/route.go
- pkg/utils/utils.go
New Traffic Path:
Out: Pod -> localGw -> Iptables(kube-proxy) -> localGw -> Policy
In : Gateway -> localGw -> Iptables(kube-proxy) -> localGw -> LocalPods
Related UT will be added in next PR
> fix(k8s-service): redesign the traffic path to enforce rules in k8s services

- cmd/everoute-controller/main.go
- deploy/everoute-controller/role.yaml
- deploy/everoute-controller/webhook.yaml
- deploy/everoute.yaml
- pkg/constants/constants.go
- pkg/controller/common/webhook_controller.go
- tests/e2e/config/webhook.yaml
+ remove secret yaml ( which will be created in controller), users can also assign their own ca by creating a secret.
+ add webhook controller, watch add and update, sync correct ca from secret.
> add webhook controller to sync ca from secret

- cmd/everoute-agent/main.go
- go.mod
- go.sum
- pkg/agent/controller/policyrule/policyrule_controller_test.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/multiBridgeDatapath_test.go
1. For ovs-vswitchd restart, replay all of flows
2. For ovsdb restart, reconnect ovsdb
> Add ovs-vswitchd and ovsdb status monitor and failover logic

- pkg/constants/constants.go
> Update comments for default tiers

- pkg/agent/datapath/multiBridgeDatapath.go
> fix: agent round num management method

- plugin/tower/pkg/informer/reflector.go
> fix(reflector): panic after disconnected with tower

- pkg/agent/datapath/multiBridgeDatapath.go
For speed up agent start, make some logic as concurrent processing
go routine
> optimize agent start logic

- pkg/agent/controller/policyrule/policyrule_controller.go
- pkg/agent/datapath/multiBridgeDatapath.go
delete and add same policyrule may be merge into one update event
> fix(policyrule): watch update for policyrule controller

- pkg/controller/policy/policy_controller.go
> refactor: return error when set IndexField failed

- pkg/agent/datapath/multiBridgeDatapath_test.go
- pkg/agent/datapath/policyBridge.go
- tests/e2e/cases/security_mode.go
If a packet matches the forensic whitelist rule, commit it directly.
> fix: forensic policy

- plugin/tower/pkg/client/client.go
> fix(tower-plugin): data race when watch from websocket stopped

- Makefile
> fix makefile images target

- skaffold.yaml
Ref to the [skaffold doc](https://skaffold.dev/docs/install/) to install skaffold. Then try `skaffold dev [-d=harbor.smartx.com/your-project]`.
> chore: Make dev deploy easier with skaffold

- pkg/controller/endpoint/endpoint_controller.go
- pkg/controller/endpoint/endpoint_controller_perf_test.go
- pkg/controller/endpoint/endpoint_controller_test.go
- pkg/monitor/agent.go
> add agent time sync logic

- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/multiBridgeDatapath.go
> add counter based ip learning rate limit

- pkg/agent/datapath/clsBridge.go
- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/multiBridgeDatapath.go
> add l2 forwarding table timeout

- go.mod
- go.sum
- pkg/agent/controller/policy/policy_controller.go
- pkg/agent/datapath/multiBridgeDatapath.go
> fix: data race while of switch disconnected

- plugin/tower/pkg/controller/endpoint/controller.go
BUG trace: http://jira.smartx.com/browse/ER-37
> fix(tower-plugin): update status error for static endpoint

- pkg/agent/datapath/localBridge.go
To cover agent failed to start or failover corner case, we add
this logic: Duplicate from local endpoint arp, send one copy to
controller, forwarding another copy normally.
> feat: duplicate from local endpoint arp in datapath

- Makefile
- build/images/release/Dockerfile
- skaffold.yaml
this arg detected from OS or pass by --plotform. If set this arg, it will not change automatically.
>  build: remove default value for TargetArch in Dockfile

- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/multiBridgeDatapath_test.go
- pkg/monitor/agent.go
- pkg/monitor/agent_test.go
> fix: refactor ovsdb interface update event processing logic

- pkg/agent/controller/policy/suite_test.go
- pkg/controller/group/suite_test.go
- pkg/controller/k8s/suite_test.go
- pkg/controller/policy/suite_test.go
- pkg/webhook/validates/suite_test.go
- plugin/tower/pkg/controller/endpoint/suite_test.go
- plugin/tower/pkg/controller/global/suite_test.go
- plugin/tower/pkg/controller/policy/suite_test.go
- tests/e2e/cases/e2e_test.go
> test: remove deprecated ginkgo custom reports

- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/multiBridgeDatapath_test.go
- pkg/monitor/agent.go
> refactor: use standard vlan instruction

- cmd/everoute-agent/config.go
- docs/cni/README.md
- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/proxy/route.go
separate pod and service traffic, pod traffic will not send to kernel in local bridge.
> fix(cni): refactor datapath for pods

- plugin/tower/pkg/schema/policy_types.go
- plugin/tower/pkg/schema/types.go
We need more fields to map mac addresses and nics.
> refactor: add more fields for tower objects

- plugin/tower/pkg/server/fake/conn/listener.go
Send to channel and close channel in the same goroutine
> refactor(tower-plugin): fix listener data race

- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/policyBridge.go
- pkg/constants/constants.go
> refactor: global policy support

- pkg/monitor/agent.go
- pkg/monitor/agent_test.go
After modification, under the same VLAN, when DHCP service is configured, the VM can obtain the IP address.
> Use "mac_in_use" to add non-vm interface as endpoint

- pkg/exporter/collector.go
Short connections only stay in EST for a very short time, and then turn into TIME_WAIT.
We will miss these conns if filter all TW status.
> feat: keep time_wait tcp conn with timeout > threshold in ctFilter

- pkg/agent/datapath/policyBridge.go
Signed-off-by: echken <echken@localhost.localdomain>
> fix: tier0 policy next table

- .github/workflows/codeql-analysis.yml
- Makefile
- go.mod
- go.sum
- pkg/agent/controller/policy/cache/helper.go
- pkg/agent/controller/policy/cache/helper_test.go
- pkg/webhook/validate.go
- pkg/webhook/validates/crd_validate.go
- plugin/tower/pkg/client/client.go
- plugin/tower/pkg/register/manager.go
- tests/e2e/framework/endpoint/tower/virsh.go
CodeQL helps discover vulnerabilities across a codebase.
> Enable codeql scanning and fix secure issues

- go.mod
- go.sum
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/multiBridgeDatapath_test.go
- pkg/agent/datapath/policyBridge.go
- pkg/exporter/collector.go
- tests/e2e/cases/security_mode.go
Signed-off-by: echken <echken@localhost.localdomain>
> fix: agent roundNum greater than maximum accepted value

- .gitignore
- pkg/exporter/uploader.go
> fix(exporter): increase kafka message size to 100MB

- pkg/agent/controller/policy/cache/rule.go
- pkg/agent/datapath/multiBridgeDatapath.go
> feat: add policy type for internal policy

- pkg/agent/datapath/localBridge.go
|tcp state|ct state|from|traffic path|to|
|--|--|--|--|--|
| syn     |    syn_sent  | pod| 65520  ->    0      |out |
| synack  |  syn_recv   |out|  0     -> 65520  -> 65510 | pod |
| ack    |     est        | pod|  65520  ->    0   | out |
|tcp state|ct state|from|traffic path|to|
|--|--|--|--|--|
| syn     |    syn_sent  | pod|65510 -> 65520  ->    0      |out |
| synack  |  syn_recv   |out|  0     -> 65520  -> 65510 | pod |
| ack    |     est        | pod| 65510 -> 65520  ->    0   | out |
> fix(cni): commit traffic not for service into cni CT zone

- Makefile
- build/images/unit-test/Dockerfile
- pkg/utils/arptables/arptables.go
- pkg/utils/arptables/arptables_test.go
> feat: add arptables utils

- plugin/tower/pkg/client/client_test.go
- plugin/tower/pkg/controller/endpoint/suite_test.go
- plugin/tower/pkg/controller/global/suite_test.go
- plugin/tower/pkg/controller/policy/suite_test.go
- plugin/tower/pkg/server/fake/conn/listener.go
- plugin/tower/pkg/server/fake/conn/listener_test.go
- plugin/tower/pkg/server/fake/server.go
- plugin/tower/pkg/server/fake/server_test.go
- plugin/tower/pkg/utils/testing/builder.go
Add testing utils to improve tests on everoute analzer.
> Add testing utils for plugin tower

- Makefile
- plugin/tower/pkg/client/client_test.go
- plugin/tower/pkg/controller/endpoint/suite_test.go
- plugin/tower/pkg/controller/global/suite_test.go
- plugin/tower/pkg/controller/policy/controller.go
- plugin/tower/pkg/controller/policy/controller_test.go
- plugin/tower/pkg/controller/policy/suite_test.go
- plugin/tower/pkg/informer/reflector.go
- plugin/tower/pkg/informer/reflector_test.go
- plugin/tower/pkg/register/manager_test.go
- plugin/tower/pkg/schema/policy_types.go
- plugin/tower/pkg/schema/policy_types.graphqls
- plugin/tower/pkg/schema/types.go
- plugin/tower/pkg/schema/types.graphqls
- plugin/tower/pkg/server/fake/conn/listener.go
- plugin/tower/pkg/server/fake/conn/listener_test.go
- plugin/tower/pkg/server/fake/graph/generated/generated.go
- plugin/tower/pkg/server/fake/server.go
- plugin/tower/pkg/server/fake/server_test.go
- plugin/tower/pkg/utils/gql.go
- plugin/tower/pkg/utils/gql_test.go
- plugin/tower/pkg/utils/testing/builder.go
- tests/e2e/framework/endpoint/tower/tower.go
> Feature visualization: cherry-pick from origin/demo

- go.mod
- go.sum
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/utils/utils.go
> feat: record datapath controller id into /var/run/everoute

- cmd/everoute-agent/main.go
- pkg/agent/datapath/localBridge.go
- pkg/monitor/agent.go
- pkg/monitor/agent_test.go
- pkg/monitor/ovsdb.go
- pkg/monitor/ovsdb_test.go
- pkg/monitor/suite_test.go
Fix http://jira.smartx.com/browse/ER-88
> refactor(agent): decouple agent and ovsdb monitor

- plugin/tower/pkg/controller/policy/controller.go
- plugin/tower/pkg/controller/policy/controller_test.go
- plugin/tower/pkg/schema/policy_types.go
- plugin/tower/pkg/schema/policy_types.graphqls
- plugin/tower/pkg/server/fake/graph/generated/generated.go
- plugin/tower/pkg/utils/testing/builder.go
Fix [ER-62](http://jira.smartx.com/browse/ER-62)
> feat(plugin-tower): support except cidr in ip block

- deploy/everoute-agent/agent.yaml
- deploy/everoute.yaml
- pkg/agent/cniserver/server.go
- pkg/agent/rpcserver/server.go
- pkg/cni/client.go
- pkg/utils/utils.go
containerd cannot mount to a directory not existed
> fix: move /var/run/everoute to /var/lib/everoute

- go.mod
- go.sum
- tests/e2e/framework/node/agent.go
cherry-pick from everoute/everoute#470
> Cherry pick fix e2e on tower to release 1.0

- plugin/tower/pkg/client/client.go
- plugin/tower/pkg/informer/factory.go
- plugin/tower/pkg/informer/reflector.go
- plugin/tower/pkg/informer/task_monitor.go
- plugin/tower/pkg/informer/task_monitor_test.go
- plugin/tower/pkg/schema/task_types.go
- plugin/tower/pkg/schema/task_types.graphqls
- plugin/tower/pkg/server/fake/graph/generated/generated.go
- plugin/tower/pkg/server/fake/graph/model/models_gen.go
- plugin/tower/pkg/server/fake/graph/query.graphqls
- plugin/tower/pkg/server/fake/graph/resolver/query.resolvers.go
- plugin/tower/pkg/server/fake/graph/resolver/tracker/factory.go
- plugin/tower/pkg/utils/testing/builder.go
- tests/e2e/framework/endpoint/tower/provider.go
cherry-pick from everoute/everoute#473
> Fix unstable e2e results on tower

- plugin/tower/pkg/client/client_test.go
- plugin/tower/pkg/controller/policy/controller.go
- plugin/tower/pkg/controller/policy/controller_test.go
- plugin/tower/pkg/informer/factory.go
- plugin/tower/pkg/informer/reflector.go
- plugin/tower/pkg/informer/reflector_test.go
- plugin/tower/pkg/register/manager.go
- plugin/tower/pkg/schema/policy_types.go
- plugin/tower/pkg/schema/policy_types.graphqls
- plugin/tower/pkg/server/fake/graph/generated/generated.go
- plugin/tower/pkg/server/fake/graph/model/models_gen.go
- plugin/tower/pkg/server/fake/graph/query.graphqls
- plugin/tower/pkg/server/fake/graph/resolver/query.resolvers.go
- plugin/tower/pkg/server/fake/graph/resolver/tracker/factory.go
- plugin/tower/pkg/utils/testing/builder.go
> Support tower security group

- plugin/tower/pkg/server/fake/conn/listener_test.go
> fix(plugin-tower): unstable test case on listener

- pkg/agent/datapath/localBridge.go
This reverts commit f40d939bd49f9dcd71e0e5a6320315878ee52c7a.
> Revert "feat(collector): clear ct commit tables for collector if existed"

- plugin/tower/pkg/client/types.go
- plugin/tower/pkg/informer/reflector.go
- plugin/tower/pkg/schema/event.go
- plugin/tower/pkg/schema/policy_types.go
- plugin/tower/pkg/schema/task_types.go
- plugin/tower/pkg/server/fake/graph/generated/generated.go
- plugin/tower/pkg/server/fake/graph/model/models_gen.go
- plugin/tower/pkg/server/fake/graph/resolver/tracker/tracker.go
> refactor(plugin-tower): use interface to handle different types

- go.mod
- go.sum
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/utils.go
- pkg/agent/datapath/utils_test.go
Use netlink library to clean conntrack entries.
~I replace the origin module, because the PR https://github.com/vishvananda/netlink/pull/819 is still in reviewing.~
> refactor(datapath): delete conntrack with netlink

- deploy/chart/crds/agent.everoute.io_agentinfos.yaml
- deploy/everoute.yaml
- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/multiBridgeDatapath_test.go
- pkg/apis/agent/v1alpha1/types.go
- pkg/constants/constants.go
- pkg/monitor/agent.go
- pkg/monitor/ovsdb.go
- pkg/monitor/ovsdb_test.go
- pkg/monitor/suite_test.go
- pkg/openapi/openapi_generated.go
support ovs port with trunks configuration.
Signed-off-by: echken <chengcheng.luo@smartx.com>
> Add vlan trunk feature

- .github/workflows/ci.yaml
- hack/0001-Skip-known-bugs-in-everoute-1.1.0.patch
- tests/e2e/cases/security_test.go
Use only version 1.1.0 of everoute.
Update self-runners please, before you merge this PR.
> Add tower-e2e-test

- pkg/agent/datapath/baseBridge.go
- pkg/agent/datapath/clsBridge.go
- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/policyBridge.go
- pkg/agent/datapath/uplinkBridge.go
add a baseBridge class to facilitate adding new bridge
> add a baseBridge class to facilitate adding new bridge

- build/script/init_agent
- cmd/everoute-agent/config.go
- cmd/everoute-agent/main.go
- deploy/chart/templates/agent/agent.yaml
- deploy/chart/values.yaml
- deploy/everoute.yaml
- pkg/agent/controller/policy/suite_test.go
- pkg/agent/datapath/clsBridge.go
- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/multiBridgeDatapath_test.go
- pkg/agent/proxy/route.go
- pkg/agent/rpcserver/cni.go
- change config to add enable proxy (Todo add update logic for config)
- create nat bridge in init-agent script
> Create bridge nat and change config

- build/script/init_agent
- pkg/agent/datapath/id_generate.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/natBridge.go
- pkg/agent/datapath/utils.go
- pkg/agent/datapath/utils_test.go
> init bridge nat

- pkg/agent/datapath/cache/svc_index.go
- pkg/agent/datapath/cache/svc_ovs_info.go
- pkg/agent/datapath/natBridge.go
svcIndex used to store service related flow and group
> feat(cni): add svcindex struct and its method

- cmd/everoute-controller/main.go
- deploy/chart/crds/service.everoute.io_serviceports.yaml
- deploy/chart/templates/controller/controller.yaml
- deploy/chart/templates/controller/role.yaml
- deploy/everoute.yaml
- pkg/apis/service/v1alpha1/types.go
- pkg/controller/k8s/endpoints_controller.go
- pkg/controller/k8s/endpoints_controller_test.go
- pkg/controller/k8s/suite_test.go
genServicePort resource according to endpoints resource
> feat(cni): genServicePort

- pkg/monitor/agent.go
Pick everoute/everoute#606 into 1.0.2
> feat(agent-monitor): only notify sync agentinfo on new address

- go.mod
- go.sum
- pkg/agent/datapath/policyBridge.go
FIX: http://jira.smartx.com/browse/ER-376
> fix(policy): filter DROP policy in EST ct item

- pkg/monitor/agent.go
> feat(monitor): only learn global unicast ip

- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/multiBridgeDatapath_test.go
- pkg/monitor/agent_test.go
- pkg/monitor/ovsdb.go
- pkg/monitor/ovsdb_test.go
- pkg/monitor/suite_test.go
Signed-off-by: echken <chengcheng.luo@smartx.com>
> refactor(monitor): update ovsdb event

- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/multiBridgeDatapath_test.go
- pkg/agent/datapath/utils.go
- pkg/agent/datapath/utils_test.go
If the input port is a vlan trunk port, should filter out packet that output from trunk port with vlan tag that is not contains in port trunk list.
> feat: vlan trunk list filter

- plugin/tower/pkg/controller/policy/controller.go
- plugin/tower/pkg/controller/policy/controller_test.go
- plugin/tower/pkg/schema/policy_types.go
- plugin/tower/pkg/schema/policy_types.graphqls
- plugin/tower/pkg/server/fake/graph/generated/generated.go
- plugin/tower/pkg/utils/testing/builder.go
根据[tower spec](http://gitlab.smartx.com/frontend/tower/-/merge_requests/10029)，在NetworkPolicyRulePort 数据结构中增加 AlgProtocol 字段
> feat(alg): support AlgProtocol field

- pkg/agent/controller/policy/policy_controller.go
- pkg/source/kind.go
- pkg/source/kind_test.go
fix [#ER-485](http://jira.smartx.com/browse/ER-485)
> fix(policy-controller): wait for all informers sync before start controllers

- pkg/agent/controller/policy/cache/group.go
- pkg/agent/controller/policy/cache/rule_test.go
- pkg/agent/controller/policy/policy_controller.go
- pkg/agent/controller/policy/policy_controller_helper.go
fix: [ER-486](http://jira.smartx.com/projects/ER/issues/ER-486?filter=allopenissues)
> fix: ip migration in different vm

- pkg/agent/proxy/route.go
cherry-pick 6848eb7175b55f93e05f41f2bd5c164480950c5b
https://github.com/everoute/everoute/pull/679
> fix(cni):delete expired iptables in EVEROUTE-OUTPUT chain

- cmd/everoute-agent/main.go
- pkg/agent/controller/overlay/controller.go
- pkg/agent/controller/overlay/suit_test.go
- pkg/controller/k8s/pod_controller_test.go
start overlay controller need to init replay channel
> fix(cni): overlay controller init replay channel

- .github/workflows/build.yaml
- .github/workflows/ci.yaml
> Revert "ci: add build cache"

- .github/workflows/ci.yaml
build runner has been login registry.smtx.io
> ci: use 'build' runner to build image for pr ci

- .github/workflows/ci.yaml
- cmd/everoute-agent/main.go
- go.mod
- go.sum
- pkg/agent/controller/proxy/cache/service_cache.go
- pkg/agent/controller/proxy/cache/service_cache_test.go
- pkg/agent/controller/proxy/controller.go
- pkg/agent/controller/proxy/controller_test.go
- pkg/agent/controller/proxy/suit_test.go
- pkg/agent/datapath/id_generate.go
- pkg/source/event.go
support  set Service.Spec.InternalTrafficPolicy
> feat(cni): support service local internal traffic policy

- cmd/everoute-controller/config.go
- cmd/everoute-controller/main.go
- deploy/chart/templates/config.yaml
- deploy/chart/templates/controller/role.yaml
- deploy/chart/templates/controller/webhook.yaml
- deploy/everoute.yaml
- pkg/constants/constants.go
- pkg/controller/common/webhook_controller.go
- 功能：
添加ipam webhook的注册和调用以及生成认证信息
- 自测：
能正常添加IP池
如果新添加的IP池与已存在的IP池 cidr有冲突，webhook报错，无法成功创建
删除已分配IP的IP池，webhook报错，无法成功删除
> feat: add ipam webhook

- pkg/monitor/agent_test.go
- pkg/monitor/ovsdb_test.go
- pkg/monitor/suite_test.go
修复 monitor 中不稳定测试，只会影响单元测试部分。
```
[root@osbuild ~]# grep "^ok" monitor-ut.log | wc -l
282
```
连续运行 200 次不会出现错误。
> test(monitor): fix unstable unit test

- pkg/agent/rpcserver/cni.go
- pkg/ipam/everoute_ipam.go
- pkg/ipam/host_local_ipam.go
- pkg/ipam/ipam.go
- pkg/types/cni.go
- pkg/utils/cni.go
把 CNIArgs 类型定义从utils目录 移到types目录
> feat: move cniargs type define from utils to types

- .github/workflows/ci.yaml
- hack/ippool_ci.yaml
添加使用 everoute ipam 时的k8s e2e
在overlay模式下，enable proxy的场景，使用everoute ipam 而不是 host-local ipam
> ci: everoute ipam ci

- .github/workflows/ci.yaml
- Makefile
- cmd/everoute-controller/config.go
- cmd/everoute-controller/main.go
- deploy/chart/templates/agent/agent.yaml
- deploy/chart/templates/agent/rolebinding.yaml
- deploy/chart/templates/agent/serviceaccount.yaml
- deploy/chart/templates/config.yaml
- deploy/chart/templates/controller/controller.yaml
- deploy/chart/templates/controller/rolebinding.yaml
- deploy/chart/templates/controller/serviceaccount.yaml
- deploy/chart/templates/controller/webhook.yaml
- deploy/chart/templates/everoute_ippool.yaml
- deploy/everoute.yaml
- hack/ippool_ci.yaml
- pkg/constants/constants.go
- pkg/controller/common/webhook_controller.go
- tests/e2e/scripts/controlplane-setup.sh
heim install 通过 -n 指定namespace
> feat: the namespace can be configured when deployed by helm

- pkg/agent/datapath/baseBridge.go
- pkg/agent/datapath/clsBridgeOverlay.go
- pkg/agent/datapath/localBridge.go
- pkg/agent/datapath/localBridgeOverlay.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/natBridge.go
- pkg/agent/datapath/policyBridge.go
- pkg/agent/datapath/uplinkBridgeOverlay.go
- pkg/agent/datapath/uplinkBridgeOverlay_test.go
- pkg/agent/datapath/utils.go
- pkg/agent/proxy/iptables/proxy_iptables.go
- pkg/constants/constants.go
tests:
- uplink bridge:
- nat bridge:
> feat: init ovs flow for kube-proxy replace feature

- plugin/tower/pkg/controller/policy/controller.go
> feat: set internal policy priority

- cmd/everoute-controller/main.go
- go.mod
- pkg/constants/constants.go
- pkg/controller/endpoint/endpoint_controller.go
- pkg/controller/endpoint/endpoint_controller_test.go
- pkg/metrics/controller_metrics.go
- pkg/metrics/ip_migrate_count.go
> feat: add controller metric

- pkg/agent/controller/policy/cache/rule.go
- pkg/agent/controller/policy/cache/rule_test.go
- pkg/agent/controller/policy/policy_controller_helper.go
- pkg/agent/datapath/multiBridgeDatapath.go
- pkg/agent/datapath/multiBridgeDatapath_test.go
- pkg/agent/datapath/policyBridge.go
- pkg/agent/datapath/utils.go
> fix(er-958): clean ct should match icmp type and code

- plugin/tower/pkg/schema/types.go
- plugin/tower/pkg/schema/types.graphqls
- plugin/tower/pkg/server/fake/graph/generated/generated.go
续：https://github.com/everoute/everoute/pull/897
> Support judge system service vm

- pkg/agent/datapath/multiBridgeDatapath.go
http://jira.smartx.com/browse/ER-1244
https://cs.smartx.com/cases/detail?id=1121121
> fix: assign tier and priority
